alias up='apt-get update'
 alias up1='apt-get upgrade'
 alias up2='apt-get dist-upgrade'
 alias install='apt-get install'
 alias remove='apt-get remove'
 alias autoremove='apt-get autoremove'
 alias clc='apt-get autoclean'
 alias ccc='clear'
 alias ee='exit'
 alias ls='ls -a'
 alias ll='ls -l'
 alias l='ls-lA'
 alias rm='rm -i'
 alias sx='source ~/.bashrc'
 alias pz='vim ~/.bashrc'
 alias cj='vim ~/.vimrc'
 alias cp='cp -i'
 alias mv='mv -i'
 alias CD='gedit /home/chyoya/Documents/cd.txt'
 alias IC='gedit /home/chyoya/Documents/iceweasel.txt'
 alias VI='gedit /home/chyoya/Documents/vim.txt'
 alias TE='gedit /home/chyoya/Documents/terminal.txt'
 alias SY='gedit /home/chyoya/Documents/随意录.txt'
 alias ~~='cd /home/chyoya/'
 alias ~x='cd /home/chyoya/Downloads/'
 alias ~w='cd /home/chyoya/Documents/'



